alertmanager:
  interval: 1m
  servers:
    - name: alertmanager
      uri: http://alertmanager:9093
      timeout: 20s
authentication:
  basicAuth:
    users:
      - username: admin
        password: admin